name: Code Quality & Accessibility

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint with detailed reporting
      run: |
        echo "🔍 Running ESLint..."
        npx eslint . --ext .ts,.tsx --format json --output-file eslint-report.json || true
        npx eslint . --ext .ts,.tsx
    
    - name: Check TypeScript compilation
      run: |
        echo "🔧 Checking TypeScript compilation..."
        npx tsc --noEmit --pretty
    
    - name: Build and check bundle size
      run: |
        echo "📦 Building and analyzing bundle..."
        npm run build
        du -sh dist/
        find dist/ -name "*.js" -exec wc -c {} + | sort -n
    
    - name: Upload code quality reports
      uses: actions/upload-artifact@v4
      with:
        name: code-quality-reports
        path: |
          eslint-report.json
          dist/
        retention-days: 7

  accessibility-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install accessibility testing tools
      run: |
        npm install -g @axe-core/cli
        npm install --save-dev @testing-library/jest-dom @axe-core/react
    
    - name: Build application
      run: npm run build
    
    - name: Start application for testing
      run: |
        npm run preview &
        sleep 10
        echo "Application started for accessibility testing"
    
    - name: Run accessibility tests
      run: |
        echo "♿ Running accessibility checks..."
        echo "Note: Add axe-core tests to your test suite for comprehensive a11y testing"
        echo "Educational platforms must meet WCAG 2.1 AA standards"
    
    - name: Accessibility compliance check
      run: |
        echo "✅ Accessibility guidelines for educational platforms:"
        echo "- WCAG 2.1 AA compliance required"
        echo "- Screen reader compatibility"
        echo "- Keyboard navigation support"
        echo "- High contrast mode support"
        echo "- Text scaling up to 200%"